apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 27.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "50"
  name: cilium
  namespace: argocd
spec:
  destination:
    namespace: cilium
    server: https://kubernetes.default.svc
  project: kubeaid
  sources:
    - repoURL: git@github.com:Obmondo/KubeAid.git
      path: argocd-helm-charts/cilium
      targetRevision: 23.0.0
      helm:
        valueFiles:
          - $values/k8s/test-local/argocd-apps/values-cilium.yaml
    - repoURL: git@github.com:waridrox/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
